import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🧪 Pengujian Klaster Komputasi AI — Lab TI UMPO\n",
            "**Workstation Multi-User Benchmark & Telemetry Test**\n",
            "\n",
            "Notebook ini dirancang untuk menguji kesiapan klaster AI Lab TI UMPO secara simultan (hingga 9–10 mahasiswa bersamaan).\n",
            "\n",
            "### 🎯 Tujuan Pengujian:\n",
            "1. **Identifikasi Akun**: Memverifikasi identitas pengguna & direktori kerja mahasiswa (`/home/m<nim>`).\n",
            "2. **Pemetaan GPU**: Memeriksa ketersediaan CUDA dan kartu GPU yang dialokasikan (GPU 0 atau GPU 1 via NVIDIA MPS).\n",
            "3. **Uji Beban GPU (Tensor Core Stress Test)**: Menjalankan perkalian matriks paralel berkecepatan tinggi untuk melihat lonjakan grafik utilisasi GPU dan VRAM di Dashboard Lab.\n",
            "4. **Uji RAM Sistem**: Memverifikasi stabilitas alokasi RAM per-user (limit kuota 4 GB).\n",
            "5. **Pelepasan Memori (Cleanup)**: Menguji pelepasan alokasi VRAM dan RAM setelah proses komputasi selesai."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ========================================================\n",
            "# 1. INFORMASI PENGGUNA & ENVIRONMENT KERNEL\n",
            "# ========================================================\n",
            "import os\n",
            "import sys\n",
            "import getpass\n",
            "import socket\n",
            "import platform\n",
            "import time\n",
            "\n",
            "print('=' * 60)\n",
            "print('🚀 INFORMASI LINGKUNGAN PENGGUNA LAB AI')\n",
            "print('=' * 60)\n",
            "print(f'👤 Username Akun   : {getpass.getuser()}')\n",
            "print(f'📁 Home Directory  : {os.path.expanduser(\"~\")}')\n",
            "print(f'💻 Node Hostname   : {socket.gethostname()}')\n",
            "print(f'🐍 Versi Python    : {sys.version.split()[0]}')\n",
            "print(f'⚙️ Sistem Operasi  : {platform.system()} {platform.release()}')\n",
            "print('=' * 60)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ========================================================\n",
            "# 2. DETEKSI GPU & CUDA RUNTIME\n",
            "# ========================================================\n",
            "try:\n",
            "    import torch\n",
            "    \n",
            "    cuda_avail = torch.cuda.is_available()\n",
            "    print('=' * 60)\n",
            "    print('🎮 STATUS HARDWARE AKSELERATOR GRAFIS (NVIDIA CUDA)')\n",
            "    print('=' * 60)\n",
            "    print(f'✅ PyTorch Version : {torch.__version__}')\n",
            "    print(f'⚡ CUDA Tersedia   : {\"YA (Aktif)\" if cuda_avail else \"TIDAK (Hanya CPU)\"}')\n",
            "    \n",
            "    if cuda_avail:\n",
            "        dev_count = torch.cuda.device_count()\n",
            "        cur_dev = torch.cuda.current_device()\n",
            "        dev_name = torch.cuda.get_device_name(cur_dev)\n",
            "        vram_free, vram_total = torch.cuda.mem_get_info()\n",
            "        \n",
            "        print(f'🔢 Jumlah GPU Terdeteksi : {dev_count}')\n",
            "        print(f'🎯 GPU Default Terpilih  : [{cur_dev}] {dev_name}')\n",
            "        print(f'💾 Total VRAM GPU        : {vram_total / (1024**3):.2f} GB')\n",
            "        print(f'🆓 Sisa VRAM Tersedia    : {vram_free / (1024**3):.2f} GB')\n",
            "        print(f'📌 CUDA Version Runtime  : {torch.version.cuda}')\n",
            "    else:\n",
            "        print('⚠️ Perhatian: CUDA belum terdeteksi aktif pada proses ini.')\n",
            "        print('🔍 Memeriksa detail diagnostik sistem...')\n",
            "        import subprocess\n",
            "        print('   - Environment CUDA_VISIBLE_DEVICES :', os.environ.get('CUDA_VISIBLE_DEVICES', 'Semua GPU'))\n",
            "        print('   - Grup User Linux                   :', subprocess.getoutput('id -Gn'))\n",
            "        print('   - Tes Perintah nvidia-smi           :')\n",
            "        smi_out = subprocess.getoutput('nvidia-smi --query-gpu=index,name,memory.total --format=csv,noheader')\n",
            "        print('     ' + smi_out.replace('\\n', '\\n     '))\n",
            "        try:\n",
            "            torch.cuda.init()\n",
            "        except Exception as err:\n",
            "            print('   - Pesan Error PyTorch CUDA Init     :', err)\n",
            "    print('=' * 60)\n",
            "except ImportError:\n",
            "    print(\"❌ Library 'torch' belum terinstall pada environment kernel ini.\")\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## ⚡ 3. Uji Beban Komputasi GPU (Matrix Multiplication Stress Test)\n",
            "Pada sel di bawah ini, kernel akan melakukan perkalian matriks besar ($4096 \\times 4096$) di dalam VRAM GPU secara berulang selama **~30 detik**.\n",
            "\n",
            "> **💡 Instruksi untuk 9 Mahasiswa:**\n",
            "> 1. Buka dashboard monitoring di tab sebelah browser: `http://<ip-server-lab>:8888`\n",
            "> 2. Klik tab **Ringkasan** dan perhatikan kartu **GPU 1** (Shared Student Pool).\n",
            "> 3. Jalankan sel kode di bawah ini bersamaan dengan rekan-rekan Anda.\n",
            "> 4. Perhatikan: Username Anda (`m<nim>`) dan nomor PID akan langsung muncul di tabel proses GPU, dan grafik utilisasi GPU akan melonjak naik secara real-time!"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ========================================================\n",
            "# 3. UJI STRESS COMPUTATION GPU (TENSOR MULTIPLICATION)\n",
            "# ========================================================\n",
            "import time\n",
            "\n",
            "if torch.cuda.is_available():\n",
            "    device = torch.device('cuda:0')\n",
            "    matrix_size = 4096  # Ukuran matriks 4096 x 4096 float32\n",
            "    iterations = 250    # Jumlah iterasi perkalian (~25-35 detik)\n",
            "    \n",
            "    print(f'🔥 Memulai alokasi tensor {matrix_size}x{matrix_size} pada {torch.cuda.get_device_name(0)}...')\n",
            "    \n",
            "    # Alokasi tensor matriks pada GPU\n",
            "    A = torch.randn(matrix_size, matrix_size, device=device, dtype=torch.float32)\n",
            "    B = torch.randn(matrix_size, matrix_size, device=device, dtype=torch.float32)\n",
            "    torch.cuda.synchronize()\n",
            "    \n",
            "    vram_used = torch.cuda.memory_allocated(device) / (1024**2)\n",
            "    print(f'📊 VRAM yang dialokasikan oleh kernel Anda saat ini: {vram_used:.1f} MB')\n",
            "    print(f'⏳ Menjalankan {iterations} iterasi perkalian matriks...')\n",
            "    print('👀 Silakan pantau Dashboard Monitoring Web Lab sekarang!')\n",
            "    print('-' * 60)\n",
            "    \n",
            "    start_time = time.time()\n",
            "    for i in range(1, iterations + 1):\n",
            "        C = torch.matmul(A, B)\n",
            "        A = A + 0.0001 * C\n",
            "        \n",
            "        if i % 50 == 0 or i == iterations:\n",
            "            torch.cuda.synchronize()\n",
            "            elapsed = time.time() - start_time\n",
            "            tflops = (2 * (matrix_size**3) * i) / (elapsed * 1e12)\n",
            "            print(f'⚡ Iterasi [{i:>3}/{iterations}] — Waktu: {elapsed:.2f}s — Throughput: ~{tflops:.2f} TFLOPS')\n",
            "            \n",
            "    torch.cuda.synchronize()\n",
            "    total_time = time.time() - start_time\n",
            "    print('-' * 60)\n",
            "    print(f'🎉 Stress Test Selesai! Total Durasi: {total_time:.2f} detik.')\n",
            "    \n",
            "    # Hapus variabel dari memori GPU\n",
            "    del A, B, C\n",
            "else:\n",
            "    print('⚠️ Pengujian GPU dilewati karena CUDA tidak aktif.')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 🧠 4. Uji Stabilitas RAM Sistem (Verifikasi Kuota 4 GB)\n",
            "Server workstation menerapkan batas isolasi RAM per-mahasiswa (maksimal **4 GB** per user).\n",
            "Pada sel di bawah ini, kita akan menguji alokasi RAM sebesar **1.5 GB** di memori CPU untuk memastikan kuota berjalan lancar dan stabil tanpa terkena OOM killer."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ========================================================\n",
            "# 4. UJI ALOKASI RAM CPU (VERIFIKASI KUOTA 4 GB)\n",
            "# ========================================================\n",
            "import numpy as np\n",
            "import psutil\n",
            "\n",
            "try:\n",
            "    print('=' * 60)\n",
            "    print('🧪 MEMULAI UJI ALOKASI MEMORI RAM CPU')\n",
            "    print('=' * 60)\n",
            "    \n",
            "    proc = psutil.Process()\n",
            "    mem_before = proc.memory_info().rss / (1024**2)\n",
            "    print(f'📊 RAM awal proses kernel : {mem_before:.1f} MB')\n",
            "    \n",
            "    # Alokasi array float64 sebesar ~1.5 GB (200 juta float64 x 8 bytes)\n",
            "    elements = 200_000_000\n",
            "    print('📦 Mengalokasikan array NumPy sebesar ~1.5 GB...')\n",
            "    large_array = np.ones(elements, dtype=np.float64)\n",
            "    \n",
            "    mem_after = proc.memory_info().rss / (1024**2)\n",
            "    print(f'📈 RAM setelah alokasi     : {mem_after:.1f} MB')\n",
            "    print('✅ Alokasi 1.5 GB RAM berhasil! Batas isolasi cgroup 4 GB aman dan stabil.')\n",
            "    \n",
            "    # Operasi sederhana pada array\n",
            "    summary = float(large_array[0] + large_array[-1])\n",
            "    print(f'🔢 Verifikasi integritas data : OK (Nilai: {summary})')\n",
            "    \n",
            "    # Bersihkan array dari RAM\n",
            "    del large_array\n",
            "    import gc\n",
            "    gc.collect()\n",
            "    \n",
            "    mem_clean = proc.memory_info().rss / (1024**2)\n",
            "    print(f'📉 RAM setelah cleanup     : {mem_clean:.1f} MB (Kembali normal)')\n",
            "    print('=' * 60)\n",
            "except MemoryError:\n",
            "    print('❌ MemoryError: Alokasi melebihi batas kuota RAM yang diizinkan.')\n",
            "except Exception as e:\n",
            "    print(f'⚠️ Terjadi error: {e}')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ========================================================\n",
            "# 5. CLEANUP VRAM & PELEPASAN SUMBER DAYA KERNEL\n",
            "# ========================================================\n",
            "import gc\n",
            "\n",
            "if torch.cuda.is_available():\n",
            "    torch.cuda.empty_cache()\n",
            "    gc.collect()\n",
            "    vram_after = torch.cuda.memory_allocated() / (1024**2)\n",
            "    print('=' * 60)\n",
            "    print('🧹 CLEANUP RESOURCE GPU & SYSTEM SELESAI')\n",
            "    print('=' * 60)\n",
            "    print(f'💾 VRAM aktif saat ini : {vram_after:.1f} MB')\n",
            "    print('✅ Seluruh cache komputasi telah dibebaskan.')\n",
            "    print('👋 Sesi pengujian selesai. Silakan cek dashboard lab untuk melihat grafik kembali normal.')\n",
            "    print('=' * 60)\n"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("/home/kiki/panel-lab (2)/uji_lab_workstation.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)

print("uji_lab_workstation.ipynb written successfully!")
